/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as TrackerIndexRouteImport } from './routes/_tracker/index'

const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerIndexRoute = TrackerIndexRouteImport.update({
  id: '/_tracker/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TrackerIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/history': typeof HistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof TrackerIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/history': typeof HistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tracker/': typeof TrackerIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/history'
  id: '__root__' | '/_tracker/' | '/dashboard/' | '/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TrackerIndexRoute: typeof TrackerIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tracker/': {
      id: '/_tracker/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TrackerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TrackerIndexRoute: TrackerIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
